services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $rootDir: '%kernel.project_dir%'
      $translationPath: '%translator.default_path%'

  CavernBay\TranslationBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Exception,Model,CavernBayTranslationBundle.php}'
        
  creatim.yaml.dumper:
    class: Symfony\Component\Yaml\Dumper

  CavernBay\TranslationBundle\Services\TranslationsImporter:
    arguments:
      $dumper: '@creatim.yaml.dumper'

#imports:
#  - { resource: commands.yml }
